"""M1-T10: paper_authors.openalex_id + org_source

Revision ID: 21e0b339dab1
Revises: 7adaa7aca171
Create Date: 2026-08-24 20:31:15.342700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21e0b339dab1'
down_revision: Union[str, Sequence[str], None] = '7adaa7aca171'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_authors', sa.Column('openalex_id', sa.String(length=50), nullable=True))
    op.add_column('paper_authors', sa.Column('org_source', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper_authors', 'org_source')
    op.drop_column('paper_authors', 'openalex_id')
    # ### end Alembic commands ###
