"""M1-T9: papers.research_tags + paper_authors.affiliation

Revision ID: 7adaa7aca171
Revises: 88c89ee51e60
Create Date: 2026-08-24 20:27:01.989452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7adaa7aca171'
down_revision: Union[str, Sequence[str], None] = '88c89ee51e60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_authors', sa.Column('affiliation', sa.Text(), nullable=True))
    op.add_column('papers', sa.Column('research_tags', postgresql.ARRAY(sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'research_tags')
    op.drop_column('paper_authors', 'affiliation')
    # ### end Alembic commands ###
