"""M1-T2: initial 11 tables

Revision ID: 88c89ee51e60
Revises: 
Create Date: 2026-08-24 19:56:15.925782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88c89ee51e60'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failed_jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_type', sa.String(length=40), nullable=False),
    sa.Column('target', sa.Text(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('name_normalized', sa.String(length=300), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_normalized')
    )
    op.create_table('papers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('arxiv_id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('authors_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('categories', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('rss_entry', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_relevant', sa.Boolean(), nullable=False),
    sa.Column('directions', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('tracks', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('arxiv_id')
    )
    op.create_table('persons',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_normalized', sa.String(length=200), nullable=False),
    sa.Column('openalex_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('openalex_id')
    )
    op.create_index('idx_persons_name', 'persons', ['name_normalized'], unique=False)
    op.create_table('token_usage',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('job_type', sa.String(length=40), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_token_usage_day', 'token_usage', ['day'], unique=False)
    op.create_table('disambiguation_queue',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('person_a_id', sa.BigInteger(), nullable=False),
    sa.Column('person_b_id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('score_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['person_a_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['person_b_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_a_id', 'person_b_id', name='uq_disamb_pair')
    )
    op.create_table('paper_authors',
    sa.Column('paper_id', sa.BigInteger(), nullable=False),
    sa.Column('author_seq', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.BigInteger(), nullable=True),
    sa.Column('raw_name', sa.String(length=200), nullable=False),
    sa.Column('name_confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('paper_id', 'author_seq')
    )
    op.create_table('person_org',
    sa.Column('person_id', sa.BigInteger(), nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('org_confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('paper_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('person_id', 'org_id')
    )
    op.create_table('person_research_tags',
    sa.Column('person_id', sa.BigInteger(), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('person_id', 'tag')
    )
    op.create_table('relationships',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('person_a_id', sa.BigInteger(), nullable=False),
    sa.Column('person_b_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('identity_confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('strength', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('coop_count', sa.Integer(), nullable=False),
    sa.Column('time_start', sa.Date(), nullable=True),
    sa.Column('time_end', sa.Date(), nullable=True),
    sa.Column('evidence_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('person_a_id < person_b_id', name='ck_rel_a_lt_b'),
    sa.ForeignKeyConstraint(['person_a_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['person_b_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_a_id', 'person_b_id', 'type')
    )
    op.create_table('relationship_evidence',
    sa.Column('relationship_id', sa.BigInteger(), nullable=False),
    sa.Column('paper_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('relationship_id', 'paper_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relationship_evidence')
    op.drop_table('relationships')
    op.drop_table('person_research_tags')
    op.drop_table('person_org')
    op.drop_table('paper_authors')
    op.drop_table('disambiguation_queue')
    op.drop_index('idx_token_usage_day', table_name='token_usage')
    op.drop_table('token_usage')
    op.drop_index('idx_persons_name', table_name='persons')
    op.drop_table('persons')
    op.drop_table('papers')
    op.drop_table('organizations')
    op.drop_table('failed_jobs')
    # ### end Alembic commands ###
